Repository For-Hives/ForVoyez, pull requests merged in 2024-06, with the labels that each got.

#261 chore: stats in readme
  README.md
Labels: documentation

#278 feat(#103): Créer les différents réseaux sociaux
  src/app/actions/contact/sendEmail.js
  src/components/Footer.component.js
Labels: feature

#289 Bug on legals redirect & refactor name properly
  src/app/(dashboard)/app/billing/layout.js
  src/app/(dashboard)/app/billing/page.js
  src/app/(dashboard)/app/legals/layout.js
  src/app/(dashboard)/app/legals/page.js
  src/app/(dashboard)/app/page.js
  src/app/(dashboard)/app/plans/layout.js
  src/app/(dashboard)/app/plans/page.js
  src/app/(dashboard)/app/usage/page.js
  src/middleware.js
Labels: bug

#297 ✨ Update image descriptions in plan features
  src/components/Dashboard/ChangingPlans.component.js
  src/components/Landing/Pricing/Pricing.component.js
Labels: feature
